// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"context"
	"github.com/hoangson1024/golang/internal/infra"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (*ApplicationContext, func(), error) {
	appConfig, err := infra.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := infra.ProvidePostgreSQL(appConfig)
	if err != nil {
		return nil, nil, err
	}
	wrapperRepo := infra.ProvideDBTestRepo(db)
	wrapper := infra.ProvideDBTestService(wrapperRepo)
	applicationContext := &ApplicationContext{
		ctx:     ctx,
		cfg:     appConfig,
		wrapper: wrapper,
	}
	return applicationContext, func() {
		cleanup()
	}, nil
}
